<?php
/**
 * Dotpay widget template
 */

// @codingStandardsIgnoreFile
/**
 * @var \Dotpay\Dotpay\Block\Widget $block
 */

/**
 * @var array
 */
$dataWidget = $block->getDataWidget();

?>
<div>
    <script>
    
    </script>
    <style type="text/css" scoped>
        form[form-target] {
            display:none;
        }
        form[form-target] input[type="submit"] {
            display:none;
            font-size: 24px;
        }
        img.mp {
            height: 60px;
        }
        img.blik {
            height: 35px;
        }
        img.dotpay {
            height: 19px;
        }
        label {
            cursor: pointer;
        }
        label input[form-target="mp"]{
            height: 60px;
        }
        label input[form-target="blik"]{
            height: 35px;
        }
        label input[form-target="dotpay"]{
            height: 19px;
        }
        label[form-target] {
            line-height: 60px;
        }
        .my-form-widget-container .dotpay-channels {
            float: left;
        }
        .my-form-widget-container + p {
            clear: both;
        }
        input[name="blik_code"] {
            width:200px;
            margin: 0px 0px 20px 0px;
        }
    </style>
    
    <p><?php echo $dataWidget['txtP']; ?></p>
    
    <?php $countStrategy = 0; ?>
    <?php foreach($dataWidget['hiddenFields'] as $keyR => $valR) : ?>
        <?php if($valR['active'] || 'dotpay' === $keyR) : ?>
            <p>
                <label form-target="<?php echo $keyR; ?>">
                    <input type="radio" name="strategy" form-target="<?php echo $keyR; ?>">
                    <img class="<?php echo $keyR; ?>" src="<?php echo $valR['icon']; ?>">
                </label>
            </p>
            <form form-target="<?php echo $keyR; ?>" method="post" action="<?php echo $dataWidget['action']; ?>">
                <?php if('dotpay' === $keyR && $dataWidget['widget']) : ?>
                    <link href="<?php echo $dataWidget['action']; ?>widget/payment_widget.min.css" rel="stylesheet">
                    <script type="text/javascript">
                        var dotpayWidgetConfig = {
                            sellerAccountId: '<?php echo $valR['fields']['id']; ?>',
                            amount: '<?php echo $valR['fields']['amount']; ?>',
                            currency: '<?php echo $valR['fields']['currency']; ?>',
                            lang: '<?php echo $valR['fields']['lang']; ?>',
                            widgetFormContainerClass: 'my-form-widget-container',
                            offlineChannel: 'mark',
                            offlineChannelTooltip: true
                        };
                    </script>
                    <script type="text/javascript" id="dotpay-payment-script" src="<?php echo $dataWidget['action']; ?>widget/payment_widget.js"></script>
                <?php endif; ?>

                <?php foreach($valR['fields'] as $keyF => $valF) : ?>
                    <input type="hidden" value="<?php echo $valF; ?>" name="<?php echo $keyF; ?>">
                <?php endforeach; ?>

                <?php if('dotpay' === $keyR && $dataWidget['widget']) : ?>
                    <p class="my-form-widget-container"></p>
                <?php endif; ?>

                <?php if('blik' === $keyR) : ?>
                    <input form-target="<?php echo $keyR; ?>" type="text" value="" name="blik_code">
                <?php endif; ?>
                
                <?php if('dotpay' !== $keyR || ('dotpay' === $keyR && $dataWidget['widget'])) : ?>
                    <?php foreach($valR['agreements'] as $keyA => $valA) : ?>
                        <p>
                            <label>
                                <input type="checkbox" name="<?php echo $keyA; ?>" value="1" checked>
                                <?php echo $valA; ?>
                            </label>
                        </p>
                    <?php endforeach; ?>
                <?php endif; ?>

                <p>
                    <input form-target="<?php echo $keyR; ?>" class="button" type="submit" value="<?php echo $dataWidget['txtSubmit']; ?>">
                </p>
            </form>
            
            <?php if($valR !== end($dataWidget['hiddenFields'])) : ?>
                <hr>
            <?php endif; ?>
            
            <?php $countStrategy++; ?>
        <?php endif; ?>
    <?php endforeach; ?>
    
    <script type="text/javascript">
        require(['jquery'], function($) {
            var isMasterPass = Boolean('<?php echo $dataWidget['mp'] ?>');
            var isBlik = Boolean('<?php echo $dataWidget['blik'] ?>');
            var isWidget = Boolean('<?php echo $dataWidget['widget'] ?>');
            
            $(document).ready(function() {
                $('form[form-target]').hide();
                
                if(!isMasterPass && !isBlik && !isWidget) {
                    $('label[form-target]').hide();
                    $('form[form-target="dotpay"]').show();
                    $('form[form-target="dotpay"] input[type="submit"]').show();
                }

                $('body').on('click', 'input[name="strategy"]', function(){
                    $('form[form-target]').hide();
                    $('form[form-target] input[type="submit"]').hide();

                    $(this).each(function(key, val){
                        var checked = $(val).is(':checked');
                        var target = $(val).attr('form-target');

                        var data = {};

                        if('mp' === target) {
                            data.type = target;
                            data.channel = $('form[form-target="' + target + '"] input[name="channel"]').val();

                            if(data.channel) {
                                $.post('<?php echo $dataWidget['signatureUrl']; ?>', data, function(result) {
                                    $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                                    submitHideShow(target);
                                });
                            }
                        } else if('blik' === target) {
                            data.type = target;
                            data.channel = $('form[form-target="' + target + '"] input[name="channel"]').val();
                            data.blik = $('form[form-target="' + target + '"] input[name="blik_code"]').val();

                            if(data.channel && data.blik) {
                                $.post('<?php echo $dataWidget['signatureUrl']; ?>', data, function(result) {
                                    $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                                    submitHideShow(target);
                                });
                            }
                        } else if('dotpay' === target) {
                            if(isWidget){
                                data.type = target;
                                data.isWidget = isWidget;
                                
                                $('form[form-target="' + target + '"] input[name="channel"]').each(function(key, val){
                                    var channel = $(val).is(':checked');
                                    var online = !$(val).parent().parent().hasClass('not-online');
                                    if(channel && online) {
                                        data.channel = $(val).val();
                                        return false;
                                    }
                                });

                                if(data.channel) {
                                    $.post('<?php echo $dataWidget['signatureUrl']; ?>', data, function(result) {
                                        $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                                        submitHideShow(target);
                                    });
                                }
                            } else {
                                submitHideShow(target);
                            }
                        }

                        if(checked) {
                           $('form[form-target="' + target + '"]').show();
                        }
                    });
                });

                $('body').on('input', 'input[name="blik_code"]', function(){
                    $('form[form-target] input[type="submit"]').hide();

                    var target = $(this).attr('form-target');

                    var data = {
                        type: target,
                        channel: $('form[form-target="' + target + '"] input[name="channel"]').val(),
                        blik: $(this).val()
                    };

                    if(data.channel && data.blik) {
                        $.post('<?php echo $dataWidget['signatureUrl']; ?>', data, function(result) {
                            $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                            submitHideShow(target);
                        });
                    }
                });

                $('body').on('click', '.channel-container', function(){
                    $('form[form-target] input[type="submit"]').hide();

                    var target = 'dotpay';
                    var data = {};
                    data.type = target;
                    data.isWidget = isWidget;

                    $('input[name="channel"]', this).each(function(key, val){
                        var channel = $(val).is(':checked');
                        var online = !$(val).parent().parent().hasClass('not-online');

                        if(channel && online) {
                            data.channel = $(val).val();
                            return false;
                        }
                    });

                    if(data.channel) {
                        $.post('<?php echo $dataWidget['signatureUrl']; ?>', data, function(result) {
                            $('form[form-target="' + target + '"] input[name="chk"]').val(result);
                            submitHideShow(target);
                        });
                    }
                });

                $('body').on('click', 'form[form-target] input[type="submit"]', function(){
                    formSubmitWait();
                    return true;
                });

                function submitHideShow(target) {
                    var result = false;

                    var checkBylaw = false;
                    var checkPersonalData = false;

                    if(target) {
                        checkBylaw = $('form[form-target="' + target + '"] input[name="bylaw"]').is(':checked');
                        checkPersonalData = $('form[form-target="' + target + '"] input[name="personal_data"]').is(':checked')
                    }

                    if('mp' === target && checkBylaw && checkPersonalData) {
                        $('form[form-target="' + target + '"] input[type="submit"]').show();
                        result = true;
                    } else if('blik' === target && checkBylaw && checkPersonalData) {
                        $('form[form-target="' + target + '"] input[type="submit"]').show();
                        result = true;
                    } else if('dotpay' === target && checkBylaw && checkPersonalData) {
                        $('form[form-target="' + target + '"] input[type="submit"]').show();
                        result = true;
                    } else if('dotpay' === target && (isMasterPass || isBlik) && !isWidget) {
                        $('form[form-target="' + target + '"] input[type="submit"]').show();
                        result = true;
                    }

                    return result;
                }

                function formSubmitWait() {
                    $('body').css('cursor', 'wait');
                }
            });
        });
        
        
    </script>
</div>
