<?php
/**
 * Dotpay widget template
 */

// @codingStandardsIgnoreFile
/**
 * @var \Dotpay\Dotpay\Block\Widget $block
 */

/**
 * @var array
 */
$dataWidget = $block->getDataWidget();

?>
<div>
    <style type="text/css" scoped>
        form[form-target] {
            /*display:none;*/
        }
        form[form-target] input[type="submit"] {
            /*display:none;*/
            font-size: 24px;
        }
        img.mp {
            height: 60px;
        }
        img.blik {
            height: 35px;
        }
        img.dotpay {
            height: 19px;
        }
        label {
            cursor: pointer;
        }
        label input[form-target="mp"]{
            height: 60px;
        }
        label input[form-target="blik"]{
            height: 35px;
        }
        label input[form-target="dotpay"]{
            height: 19px;
        }
        label[form-target] {
            line-height: 60px;
        }
        .my-form-widget-container .dotpay-channels {
            float: left;
        }
        .my-form-widget-container + p {
            clear: both;
        }
        input[name="blik_code"] {
            width:200px;
            margin: 0px 0px 20px 0px;
        }
    </style>
    
    <p><?php echo $dataWidget['txtP']; ?></p>
    
    <?php $countStrategy = 0; ?>
    <?php foreach($dataWidget['hiddenFields'] as $keyR => $valR) : ?>
        <?php if($valR['active']) : ?>
            <p>
                <label form-target="<?php echo $keyR; ?>">
                    <input type="radio" name="strategy" form-target="<?php echo $keyR; ?>">
                    <img class="<?php echo $keyR; ?>" src="<?php echo $valR['icon']; ?>">
                </label>
            </p>
            <form form-target="<?php echo $keyR; ?>" method="post" action="<?php echo $dataWidget['action']; ?>">
                <?php if('dotpay' === $keyR) : ?>
                    <link href="<?php echo $dataWidget['action']; ?>widget/payment_widget.min.css" rel="stylesheet">
                    <script type="text/javascript" id="dotpay-payment-script" src="<?php echo $dataWidget['action']; ?>widget/payment_widget.js"></script>
                    <script type="text/javascript">
                        var dotpayWidgetConfig = {
                            sellerAccountId: '<?php echo $valR['fields']['id']; ?>',
                            amount: '<?php echo $valR['fields']['amount']; ?>',
                            currency: '<?php echo $valR['fields']['currency']; ?>',
                            lang: '<?php echo $valR['fields']['lang']; ?>',
                            widgetFormContainerClass: 'my-form-widget-container',
                            offlineChannel: 'mark',
                            offlineChannelTooltip: true
                        };
                    </script>
                <?php endif; ?>

                <?php foreach($valR['fields'] as $keyF => $valF) : ?>
                    <input type="hidden" value="<?php echo $valF; ?>" name="<?php echo $keyF; ?>">
                <?php endforeach; ?>

                <?php if('dotpay' === $keyR) : ?>
                    <p class="my-form-widget-container"></p>
                <?php endif; ?>

                <?php if('blik' === $keyR) : ?>
                    <input form-target="<?php echo $keyR; ?>" type="text" value="" name="blik_code">
                <?php endif; ?>

                <?php foreach($valR['agreements'] as $keyA => $valA) : ?>
                    <p>
                        <label>
                            <input type="checkbox" name="<?php echo $keyA; ?>" value="1" checked>
                            <?php echo $valA; ?>
                        </label>
                    </p>
                <?php endforeach; ?>

                <p>
                    <input form-target="<?php echo $keyR; ?>" class="button" type="submit" value="<?php echo $dataWidget['txtSubmit']; ?>">
                </p>
            </form>
            
            <?php if($valR !== end($dataWidget['hiddenFields'])) : ?>
                <hr>
            <?php endif; ?>
            
            <?php $countStrategy++; ?>
        <?php endif; ?>
    <?php endforeach; ?>
    
</div>





<?php return; ?>
<div>
    <form id="redirectDotpay" method="post" action="<?php echo $dataWidget['action']; ?>">
        <p><?php echo $dataWidget['txtP']; ?></p>
        
        <link href="<?php echo $dataWidget['action']; ?>widget/payment_widget.min.css" rel="stylesheet">
        <script type="text/javascript" id="dotpay-payment-script" src="<?php echo $dataWidget['action']; ?>widget/payment_widget.js"></script>
        <script type="text/javascript">
            var dotpayWidgetConfig = {
                sellerAccountId: '<?php echo $dataWidget['hiddenFields']['id']; ?>',
                amount: '<?php echo $dataWidget['hiddenFields']['amount']; ?>',
                currency: '<?php echo $dataWidget['hiddenFields']['currency']; ?>',
                lang: '<?php echo $dataWidget['hiddenFields']['lang']; ?>',
                widgetFormContainerClass: 'my-form-widget-container',
                offlineChannel: 'mark',
                offlineChannelTooltip: true
            };
        </script>
        
        <p class="my-form-widget-container"></p>
        
        <p>
            <label>
                <input type="checkbox" id="bylaw" name="bylaw" value="1" checked>
                <?php echo $dataWidget['agreement_bylaw']; ?>
            </label>
        </p>
        <p>
            <label>
                <input type="checkbox" id="personal_data" name="personal_data" value="1" checked>
                <?php echo $dataWidget['agreement_personal_data']; ?>
            </label>
        </p>

        <p class="form-submit">
            <?php foreach($dataWidget['hiddenFields'] as $k => $v) : ?>
                <input type="hidden" value="<?php echo $v; ?>" name="<?php echo $k; ?>">
            <?php endforeach; ?>
            <input id="submit_dotpay_payment_form" class="button" type="submit" value="<?php echo $dataWidget['txtSubmit']; ?>">
        </p>
        
        <style type="text/css" scoped>
            .my-form-widget-container .dotpay-channels {
                float: left;
            }
            .my-form-widget-container + p {
                clear: both;
            }
            #submit_dotpay_payment_form {
                font-size: 24px;
            }
        </style>
        
        <script type="text/javascript">
            $('#submit_dotpay_payment_form').hide();

            $(document).ready(function() {
                var checkChannel = false;

                function submitHideShow() {
                    var checkBylaw = $('#bylaw').is(':checked');
                    var checkPersonalData = $('#personal_data').is(':checked')

                    if(checkChannel && checkBylaw && checkPersonalData) {
                        $('#submit_dotpay_payment_form').show();
                    } else {
                        $('#submit_dotpay_payment_form').hide();
                    }
                }

                $('body').on('click', '.channel-container', function(){
                    if($(this).hasClass('not-online')) {
                         checkChannel = false;
                    } else {
                        checkChannel = true;
                    }
                    submitHideShow();
                });

                $('body').on('click', '#bylaw', submitHideShow);
                $('body').on('click', '#personal_data', submitHideShow);
                
                $('body').on('click', '#submit_dotpay_payment_form', function(){
                    var channel;
                
                    $('input[name="channel"]').each(function(key, val){
                        var checked = $(val).is(':checked');
                        if(checked) {
                            channel = $(val).val();
                            return false;
                        }
                    });

                    var data = {
                        channel: channel
                    };

                    if(channel) {
                        $.post('<?php echo $dataWidget['signatureUrl']; ?>', data, function(result) {
                            $('input[name="CHK"]').val(result);
                            $('body').css('cursor', 'wait');
                            $('#redirectDotpay').submit();
                        });
                    }

                    return false;
                });
            });
        </script>
    </form>
</div>
