<?php
/**
 * Dotpay widget template
 */

// @codingStandardsIgnoreFile
/**
 * @var \Dotpay\Dotpay\Block\Widget $block
 */

/**
 * @var array
 */
$dataWidget = $block->getDataWidget();

?>
<div>
    <form method="post" action="<?php echo $dataWidget['action']; ?>">
        <p><?php echo $dataWidget['txtP']; ?></p>
        
        <link href="<?php echo $dataWidget['action']; ?>widget/payment_widget.min.css" rel="stylesheet">
        <script type="text/javascript" id="dotpay-payment-script" src="<?php echo $dataWidget['action']; ?>widget/payment_widget.js"></script>
        <script type="text/javascript">
            var dotpayWidgetConfig = {
                sellerAccountId: '<?php echo $dataWidget['hiddenFields']['id']; ?>',
                amount: '<?php echo $dataWidget['hiddenFields']['amount']; ?>',
                currency: '<?php echo $dataWidget['hiddenFields']['currency']; ?>',
                lang: '<?php echo $dataWidget['hiddenFields']['lang']; ?>',
                widgetFormContainerClass: 'my-form-widget-container',
                offlineChannel: 'mark',
                offlineChannelTooltip: true
            };
        </script>
        
        
        
        <p class="my-form-widget-container"></p>

        <p class="form-submit">
            <?php foreach($dataWidget['hiddenFields'] as $k => $v) : ?>
                <input type="hidden" value="<?php echo $v; ?>" name="<?php echo $k; ?>">
            <?php endforeach; ?>
            <input id="submit_dotpay_payment_form" class="button" type="submit" value="<?php echo $dataWidget['txtSubmit']; ?>">
        </p>
        
        <style type="text/css" scoped>
            .my-form-widget-container .dotpay-channels {
                float: left;
            }
            .form-submit {
                clear: both;
            }
            #submit_dotpay_payment_form {
                font-size: 24px;
            }
        </style>
    </form>
</div>
